In [1]:
import pandas as pd
df = pd.read_csv("tickets.csv")
df.head()

,ticket_id,short_description,category,subcategory,issue_type
0,1,Unable to connect to VPN from home network,Network,VPN,Access Issue
1,2,Outlook not sending emails,Software,MS Outlook,Email Issue
2,3,Laptop screen flickering intermittently,Hardware,Display,Performance Issue
3,4,Password reset not working for AD account,Access Management,Active Directory,Access Issue
4,5,WiFi disconnects frequently in office,Network,WiFi,Connectivity Issue

In [3]:
!pip install nltk

Collecting nltk
  Downloading nltk-3.9.3-py3-none-any.whl (1.5 MB)
                                              0.0/1.5 MB ? eta -:--:--
     -                                        0.0/1.5 MB 991.0 kB/s eta 0:00:02
     -----                                    0.2/1.5 MB 2.8 MB/s eta 0:00:01
     -----------                              0.4/1.5 MB 3.3 MB/s eta 0:00:01
     ---------------                          0.6/1.5 MB 3.4 MB/s eta 0:00:01
     ------------------                       0.7/1.5 MB 3.2 MB/s eta 0:00:01
     -------------------------                1.0/1.5 MB 3.6 MB/s eta 0:00:01
     -----------------------------            1.1/1.5 MB 3.6 MB/s eta 0:00:01
     -----------------------------------      1.3/1.5 MB 3.9 MB/s eta 0:00:01
     ---------------------------------------  1.5/1.5 MB 3.9 MB/s eta 0:00:01
     ---------------------------------------  1.5/1.5 MB 3.9 MB/s eta 0:00:01
     ---------------------------------------- 1.5/1.5 MB 3.0 MB/s eta 0:00:00
Requirement already satisfied: click in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from nltk) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from nltk) (2025.7.34)
Requirement already satisfied: tqdm in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from click->nltk) (0.4.6)
Installing collected packages: nltk
Successfully installed nltk-3.9.3

[notice] A new release of pip is available: 23.1.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:

import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    words = text.split()
    words = [word for word in words if word not in stop_words]
    return " ".join(words)

df['clean_text'] = df['short_description'].apply(clean_text)

df[['short_description', 'clean_text']].head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Mansi\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

,short_description,clean_text
0,Unable to connect to VPN from home network,unable connect vpn home network
1,Outlook not sending emails,outlook sending emails
2,Laptop screen flickering intermittently,laptop screen flickering intermittently
3,Password reset not working for AD account,password reset working ad account
4,WiFi disconnects frequently in office,wifi disconnects frequently office

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df['clean_text'])
y = df['category']

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.3
              precision    recall  f1-score   support

    Hardware       1.00      0.25      0.40         4
     Network       0.12      1.00      0.22         1
    Software       1.00      0.20      0.33         5

    accuracy                           0.30        10
   macro avg       0.71      0.48      0.32        10
weighted avg       0.91      0.30      0.35        10

In [7]:
df['predicted_category'] = model.predict(X)

df['validation_flag'] = df.apply(
    lambda row: "Mismatch" if row['category'] != row['predicted_category'] else "Correct",
    axis=1
)

df[['ticket_id', 'category', 'predicted_category', 'validation_flag']].head()

   ticket_id           category predicted_category validation_flag
0          1            Network            Network         Correct
1          2           Software           Software         Correct
2          3           Hardware           Hardware         Correct
3          4  Access Management  Access Management         Correct
4          5            Network            Network         Correct

In [8]:
# Get prediction probabilities
probs = model.predict_proba(X)

# Get max probability for each prediction
import numpy as np
confidence_scores = np.max(probs, axis=1)

df['confidence_score'] = confidence_scores
df['predicted_category'] = model.predict(X)

In [9]:
def validate_ticket(row):
    if row['category'] != row['predicted_category']:
        return "Mismatch"
    elif row['confidence_score'] < 0.60:
        return "Low Confidence"
    else:
        return "Correct"

df['validation_flag'] = df.apply(validate_ticket, axis=1)

df[['ticket_id', 'category', 'predicted_category', 
    'confidence_score', 'validation_flag']].head()

,ticket_id,category,predicted_category,confidence_score,validation_flag
0,1,Network,Network,0.535979,Low Confidence
1,2,Software,Software,0.418502,Low Confidence
2,3,Hardware,Hardware,0.409062,Low Confidence
3,4,Access Management,Access Management,0.421267,Low Confidence
4,5,Network,Network,0.482304,Low Confidence

In [10]:
df['validation_flag'].value_counts()

validation_flag
Low Confidence    43
Mismatch           7
Name: count, dtype: int64

In [11]:
mismatch_percentage = (df['validation_flag'].value_counts(normalize=True) * 100)
print(mismatch_percentage)

validation_flag
Low Confidence    86.0
Mismatch          14.0
Name: proportion, dtype: float64

In [12]:
import pickle

# Save model
with open("ticket_classifier.pkl", "wb") as f:
    pickle.dump(model, f)

# Save vectorizer
with open("tfidf_vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

print("Model and vectorizer saved successfully.")

Model and vectorizer saved successfully.

In [13]:
import numpy as np

feature_names = vectorizer.get_feature_names_out()

for i, category in enumerate(model.classes_):
    top10 = np.argsort(model.coef_[i])[-10:]
    print(f"\nTop words for {category}:")
    print([feature_names[j] for j in top10])

Top words for Access Management:
['employee', 'finance', 'revoked', 'incorrectly', 'user', 'account', 'multiple', 'new', 'access', 'need']

Top words for Hardware:
['heavy', 'usage', 'overheating', 'printing', 'documents', 'printer', 'running', 'turning', 'monitor', 'laptop']

Top words for Network:
['authentication', 'website', 'loading', 'desktop', 'frequently', 'network', 'internal', 'drive', 'vpn', 'internet']

Top words for Software:
['emails', 'sending', 'payroll', 'attachments', 'downloading', 'unable', 'software', 'file', 'crashing', 'update']

In [14]:
pip install sentence-transformers

Requirement already satisfied: sentence-transformers in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (5.1.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from sentence-transformers) (4.55.3)
Requirement already satisfied: tqdm in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from sentence-transformers) (2.8.0)
Requirement already satisfied: scikit-learn in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from sentence-transformers) (1.16.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from sentence-transformers) (0.34.4)
Requirement already satisfied: Pillow in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from sentence-transformers) (10.0.0)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from sentence-transformers) (4.14.1)
Requirement already satisfied: filelock in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.19.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.1)
Requirement already satisfied: requests in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.5)
Requirement already satisfied: sympy>=1.13.3 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.2)
Requirement already satisfied: colorama in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: numpy>=1.17 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.3.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.7.34)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.6.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn->sentence-transformers) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2023.7.22)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.1.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

model_embed = SentenceTransformer('all-MiniLM-L6-v2')

embeddings = model_embed.encode(df['short_description'])
sim_matrix = cosine_similarity(embeddings)

In [16]:
!pip install streamlit

Collecting streamlit
  Downloading streamlit-1.54.0-py3-none-any.whl (9.1 MB)
                                              0.0/9.1 MB ? eta -:--:--
                                              0.1/9.1 MB 2.0 MB/s eta 0:00:05
     -                                        0.3/9.1 MB 2.6 MB/s eta 0:00:04
     -                                        0.4/9.1 MB 2.6 MB/s eta 0:00:04
     --                                       0.5/9.1 MB 2.8 MB/s eta 0:00:04
     --                                       0.6/9.1 MB 2.7 MB/s eta 0:00:04
     ---                                      0.8/9.1 MB 2.7 MB/s eta 0:00:04
     ----                                     1.0/9.1 MB 2.9 MB/s eta 0:00:03
     ----                                     1.1/9.1 MB 3.0 MB/s eta 0:00:03
     -----                                    1.3/9.1 MB 3.1 MB/s eta 0:00:03
     ------                                   1.5/9.1 MB 3.1 MB/s eta 0:00:03
     -------                                  1.6/9.1 MB 3.1 MB/s eta 0:00:03
     -------                                  1.8/9.1 MB 3.2 MB/s eta 0:00:03
     --------                                 1.9/9.1 MB 3.1 MB/s eta 0:00:03
     ---------                                2.1/9.1 MB 3.2 MB/s eta 0:00:03
     ---------                                2.2/9.1 MB 3.1 MB/s eta 0:00:03
     ----------                               2.4/9.1 MB 3.2 MB/s eta 0:00:03
     -----------                              2.5/9.1 MB 3.2 MB/s eta 0:00:03
     -----------                              2.7/9.1 MB 3.2 MB/s eta 0:00:02
     ------------                             2.9/9.1 MB 3.3 MB/s eta 0:00:02
     -------------                            3.0/9.1 MB 3.2 MB/s eta 0:00:02
     -------------                            3.2/9.1 MB 3.2 MB/s eta 0:00:02
     --------------                           3.4/9.1 MB 3.3 MB/s eta 0:00:02
     ---------------                          3.5/9.1 MB 3.3 MB/s eta 0:00:02
     ----------------                         3.7/9.1 MB 3.3 MB/s eta 0:00:02
     ----------------                         3.8/9.1 MB 3.3 MB/s eta 0:00:02
     -----------------                        4.0/9.1 MB 3.3 MB/s eta 0:00:02
     ------------------                       4.1/9.1 MB 3.3 MB/s eta 0:00:02
     ------------------                       4.3/9.1 MB 3.3 MB/s eta 0:00:02
     -------------------                      4.5/9.1 MB 3.3 MB/s eta 0:00:02
     --------------------                     4.6/9.1 MB 3.3 MB/s eta 0:00:02
     ---------------------                    4.8/9.1 MB 3.3 MB/s eta 0:00:02
     ---------------------                    5.0/9.1 MB 3.3 MB/s eta 0:00:02
     ----------------------                   5.1/9.1 MB 3.4 MB/s eta 0:00:02
     -----------------------                  5.3/9.1 MB 3.4 MB/s eta 0:00:02
     -----------------------                  5.4/9.1 MB 3.4 MB/s eta 0:00:02
     ------------------------                 5.6/9.1 MB 3.3 MB/s eta 0:00:02
     ------------------------                 5.7/9.1 MB 3.3 MB/s eta 0:00:02
     -------------------------                5.9/9.1 MB 3.3 MB/s eta 0:00:01
     --------------------------               6.0/9.1 MB 3.3 MB/s eta 0:00:01
     --------------------------               6.2/9.1 MB 3.3 MB/s eta 0:00:01
     ---------------------------              6.3/9.1 MB 3.3 MB/s eta 0:00:01
     ----------------------------             6.4/9.1 MB 3.3 MB/s eta 0:00:01
     ----------------------------             6.5/9.1 MB 3.3 MB/s eta 0:00:01
     -----------------------------            6.6/9.1 MB 3.3 MB/s eta 0:00:01
     -----------------------------            6.8/9.1 MB 3.3 MB/s eta 0:00:01
     -----------------------------            6.8/9.1 MB 3.3 MB/s eta 0:00:01
     -----------------------------            6.8/9.1 MB 3.3 MB/s eta 0:00:01
     -----------------------------            6.8/9.1 MB 3.3 MB/s eta 0:00:01
     -----------------------------            6.8/9.1 MB 3.3 MB/s eta 0:00:01
     -----------------------------            6.8/9.1 MB 3.3 MB/s eta 0:00:01
     -----------------------------            6.8/9.1 MB 3.3 MB/s eta 0:00:01
     -----------------------------            6.8/9.1 MB 3.3 MB/s eta 0:00:01
     ------------------------------           6.8/9.1 MB 2.8 MB/s eta 0:00:01
     ------------------------------           6.9/9.1 MB 2.8 MB/s eta 0:00:01
     ------------------------------           7.1/9.1 MB 2.8 MB/s eta 0:00:01
     -------------------------------          7.2/9.1 MB 2.8 MB/s eta 0:00:01
     --------------------------------         7.4/9.1 MB 2.8 MB/s eta 0:00:01
     --------------------------------         7.4/9.1 MB 2.8 MB/s eta 0:00:01
     --------------------------------         7.5/9.1 MB 2.8 MB/s eta 0:00:01
     ---------------------------------        7.6/9.1 MB 2.8 MB/s eta 0:00:01
     ---------------------------------        7.6/9.1 MB 2.8 MB/s eta 0:00:01
     ---------------------------------        7.6/9.1 MB 2.8 MB/s eta 0:00:01
     ---------------------------------        7.6/9.1 MB 2.8 MB/s eta 0:00:01
     ---------------------------------        7.6/9.1 MB 2.8 MB/s eta 0:00:01
     ---------------------------------        7.6/9.1 MB 2.5 MB/s eta 0:00:01
     ----------------------------------       7.8/9.1 MB 2.5 MB/s eta 0:00:01
     -----------------------------------      8.0/9.1 MB 2.5 MB/s eta 0:00:01
     ------------------------------------     8.2/9.1 MB 2.6 MB/s eta 0:00:01
     ------------------------------------     8.4/9.1 MB 2.6 MB/s eta 0:00:01
     -------------------------------------    8.5/9.1 MB 2.6 MB/s eta 0:00:01
     --------------------------------------   8.7/9.1 MB 2.6 MB/s eta 0:00:01
     --------------------------------------   8.9/9.1 MB 2.6 MB/s eta 0:00:01
     ---------------------------------------  8.9/9.1 MB 2.6 MB/s eta 0:00:01
     ---------------------------------------  9.1/9.1 MB 2.6 MB/s eta 0:00:01
     ---------------------------------------  9.1/9.1 MB 2.6 MB/s eta 0:00:01
     ---------------------------------------  9.1/9.1 MB 2.6 MB/s eta 0:00:01
     ---------------------------------------  9.1/9.1 MB 2.6 MB/s eta 0:00:01
     ---------------------------------------  9.1/9.1 MB 2.6 MB/s eta 0:00:01
     ---------------------------------------- 9.1/9.1 MB 2.5 MB/s eta 0:00:00
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Downloading altair-6.0.0-py3-none-any.whl (795 kB)
                                              0.0/795.4 kB ? eta -:--:--
     --------                               174.1/795.4 kB 3.5 MB/s eta 0:00:01
     ---------------                        317.4/795.4 kB 3.3 MB/s eta 0:00:01
     ------------------------               522.2/795.4 kB 3.6 MB/s eta 0:00:01
     ------------------------------         645.1/795.4 kB 3.4 MB/s eta 0:00:01
     -------------------------------------  788.5/795.4 kB 3.6 MB/s eta 0:00:01
     -------------------------------------- 795.4/795.4 kB 3.3 MB/s eta 0:00:00
Collecting blinker<2,>=1.5.0 (from streamlit)
  Using cached blinker-1.9.0-py3-none-any.whl (8.5 kB)
Requirement already satisfied: cachetools<7,>=5.5 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (6.1.0)
Requirement already satisfied: click<9,>=7.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (8.2.1)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading gitpython-3.1.46-py3-none-any.whl (208 kB)
                                              0.0/208.6 kB ? eta -:--:--
     --------------------------             143.4/208.6 kB 4.3 MB/s eta 0:00:01
     -------------------------------------  204.8/208.6 kB 4.1 MB/s eta 0:00:01
     -------------------------------------  204.8/208.6 kB 4.1 MB/s eta 0:00:01
     -------------------------------------  204.8/208.6 kB 4.1 MB/s eta 0:00:01
     -------------------------------------- 208.6/208.6 kB 1.1 MB/s eta 0:00:00
Requirement already satisfied: numpy<3,>=1.23 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (2.3.2)
Requirement already satisfied: packaging>=20 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (2.3.1)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (10.0.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Using cached pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (6.32.0)
Requirement already satisfied: pyarrow>=7.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (9.1.2)
Collecting toml<2,>=0.10.1 (from streamlit)
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (6.3.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (4.14.1)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Using cached watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)
Requirement already satisfied: jinja2 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.2)
Requirement already satisfied: jsonschema>=3.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.25.1)
Collecting narwhals>=1.27.1 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading narwhals-2.17.0-py3-none-any.whl (444 kB)
                                              0.0/444.9 kB ? eta -:--:--
     ------------                           143.4/444.9 kB 4.3 MB/s eta 0:00:01
     ------------------------               286.7/444.9 kB 3.5 MB/s eta 0:00:01
     ----------------------------------     399.4/444.9 kB 3.1 MB/s eta 0:00:01
     -------------------------------------- 444.9/444.9 kB 2.8 MB/s eta 0:00:00
Requirement already satisfied: colorama in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached gitdb-4.0.12-py3-none-any.whl (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (2023.7.22)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached smmap-5.0.2-py3-none-any.whl (24 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.9.2)
Requirement already satisfied: six>=1.5 in c:\users\mansi\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.16.0)
Installing collected packages: watchdog, toml, smmap, narwhals, blinker, pydeck, gitdb, gitpython, altair, streamlit
Successfully installed altair-6.0.0 blinker-1.9.0 gitdb-4.0.12 gitpython-3.1.46 narwhals-2.17.0 pydeck-0.9.1 smmap-5.0.2 streamlit-1.54.0 toml-0.10.2 watchdog-6.0.0

[notice] A new release of pip is available: 23.1.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
import streamlit as st
import pickle
import numpy as np

# Load model
model = pickle.load(open("ticket_classifier.pkl", "rb"))
vectorizer = pickle.load(open("tfidf_vectorizer.pkl", "rb"))

st.title("IT Ticket Validation System")

user_input = st.text_input("Enter Ticket Description")

if user_input:
    text_vec = vectorizer.transform([user_input])
    prediction = model.predict(text_vec)[0]
    confidence = np.max(model.predict_proba(text_vec))
    
    st.write("Predicted Category:", prediction)
    st.write("Confidence Score:", round(confidence, 2))
    
    if confidence < 0.6:
        st.warning("Low Confidence - Manual Review Suggested")

2026-03-02 17:30:44.510 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-02 17:30:45.003
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run c:\Users\Mansi\AppData\Local\Programs\Python\Python311\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-03-02 17:30:45.004 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-02 17:30:45.005 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-02 17:30:45.006 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-02 17:30:45.007 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-02 17:30:45.008 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-02 17:30:45.010 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-02 17:30:45.011 Session state does not function when running a script without `streamlit run`
2026-03-02 17:30:45.014 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-02 17:30:45.015 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-02 17:30:45.019 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.